"""initial schema

Revision ID: bc6c46e1d93b
Revises: 
Create Date: 2026-05-03 21:37:16.576597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc6c46e1d93b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('verification_tokens',
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('identifier', 'token')
    )
    op.create_table('organization_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('schedule_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_periods_organization_id'), ['organization_id'], unique=False)

    op.create_table('shift_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_slots_organization_id'), ['organization_id'], unique=False)

    op.create_table('solver_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('max_consecutive_days', sa.Integer(), nullable=False),
    sa.Column('time_limit', sa.Integer(), nullable=False),
    sa.Column('min_shift_interval_hours', sa.Integer(), nullable=False),
    sa.Column('enable_preferred_shift', sa.Boolean(), nullable=False),
    sa.Column('enable_fairness', sa.Boolean(), nullable=False),
    sa.Column('enable_weekend_fairness', sa.Boolean(), nullable=False),
    sa.Column('enable_shift_interval', sa.Boolean(), nullable=False),
    sa.Column('enable_role_staffing', sa.Boolean(), nullable=False),
    sa.Column('enable_min_days_per_week', sa.Boolean(), nullable=False),
    sa.Column('enable_soft_staffing', sa.Boolean(), nullable=False),
    sa.Column('enable_reverse_cycle_prohibition', sa.Boolean(), nullable=False),
    sa.Column('enable_skill_staffing', sa.Boolean(), nullable=False),
    sa.Column('weight_preferred', sa.Float(), nullable=False),
    sa.Column('weight_fairness', sa.Float(), nullable=False),
    sa.Column('weight_weekend_fairness', sa.Float(), nullable=False),
    sa.Column('weight_soft_staffing', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solver_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solver_config_organization_id'), ['organization_id'], unique=False)

    op.create_table('staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('max_days_per_week', sa.Integer(), nullable=False),
    sa.Column('min_days_per_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_organization_id'), ['organization_id'], unique=False)

    op.create_table('role_staffing_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('shift_slot_id', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('min_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_slot_id'], ['shift_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role_staffing_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_staffing_requirements_organization_id'), ['organization_id'], unique=False)

    op.create_table('schedule_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_slot_id', sa.Integer(), nullable=True),
    sa.Column('is_manual_edit', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['schedule_periods.id'], ),
    sa.ForeignKeyConstraint(['shift_slot_id'], ['shift_slots.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_assignments_organization_id'), ['organization_id'], unique=False)

    op.create_table('skill_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('shift_slot_id', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.String(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.Column('min_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_slot_id'], ['shift_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_requirements_organization_id'), ['organization_id'], unique=False)

    op.create_table('staff_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift_slot_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_slot_id'], ['shift_slots.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_requests_organization_id'), ['organization_id'], unique=False)

    op.create_table('staff_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('skill', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staff_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_skills_organization_id'), ['organization_id'], unique=False)

    op.create_table('staffing_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('shift_slot_id', sa.Integer(), nullable=False),
    sa.Column('day_type', sa.String(), nullable=False),
    sa.Column('min_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['shift_slot_id'], ['shift_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('staffing_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staffing_requirements_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffing_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staffing_requirements_organization_id'))

    op.drop_table('staffing_requirements')
    with op.batch_alter_table('staff_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_skills_organization_id'))

    op.drop_table('staff_skills')
    with op.batch_alter_table('staff_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_requests_organization_id'))

    op.drop_table('staff_requests')
    with op.batch_alter_table('skill_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_requirements_organization_id'))

    op.drop_table('skill_requirements')
    with op.batch_alter_table('schedule_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_assignments_organization_id'))

    op.drop_table('schedule_assignments')
    with op.batch_alter_table('role_staffing_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_staffing_requirements_organization_id'))

    op.drop_table('role_staffing_requirements')
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_organization_id'))

    op.drop_table('staff')
    with op.batch_alter_table('solver_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solver_config_organization_id'))

    op.drop_table('solver_config')
    with op.batch_alter_table('shift_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_slots_organization_id'))

    op.drop_table('shift_slots')
    with op.batch_alter_table('schedule_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_periods_organization_id'))

    op.drop_table('schedule_periods')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_organization_id'))

    op.drop_table('organization_members')
    op.drop_table('verification_tokens')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
